name: Test Nginx Proxy - HTTP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-nginx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: List files (debug)
      run: |
        echo "Repository contents:"
        ls -la
        echo "Docker version:"
        docker --version
        docker compose version
    
    - name: Check Docker Compose file
      run: |
        if [ -f "nginx-compose.yml" ]; then
          echo "✅ nginx-compose.yml found"
          cat nginx-compose.yml
        else
          echo "❌ nginx-compose.yml not found"
          exit 1
        fi
    
    - name: Test Docker Compose syntax
      run: |
        docker compose -f nginx-compose.yml config
    
    - name: Start Nginx service
      run: |
        docker compose -f nginx-compose.yml up -d
        echo "Waiting for nginx to start..."
        sleep 15
    
    - name: Check running containers
      run: |
        docker ps
        docker compose -f nginx-compose.yml ps
    
    - name: Test HTTP response
      run: |
        echo "Testing HTTP response..."
        response=$(curl -s http://localhost/ || echo "CURL_FAILED")
        echo "Response: $response"
        if [[ $response == *"Hello World"* ]]; then
          echo "✅ HTTP test passed - Found expected content"
        else
          echo "❌ HTTP test failed - Expected content not found"
          echo "Full response: $response"
        fi
        
    - name: Show nginx logs (if needed)
      if: failure()
      run: |
        docker compose -f nginx-compose.yml logs nginx
        
    - name: Cleanup
      if: always()
      run: |
        docker compose -f nginx-compose.yml down